# Generated by Django 4.1 on 2024-05-25 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Shape',
        ),
        migrations.RenameField(
            model_name='shape',
            old_name='text',
            new_name='shape_text',
        ),
    ]
