# Generated by Django 4.1 on 2024-05-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0002_rename_topic_shape_rename_text_shape_shape_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
